playerspawn:
  X: -9.5
  Y: 5.0
  Z: 4.5
  world: world
taggerspawn:
  X: -13.5
  Y: 5.0
  Z: 9.5
  world: world
lobbyspawn:
  X: 1
  Y: 1
  Z: 1
  world: world
  
max-players: 6
min-players: 2
taggers: 1
tagger-delay: 10
power-potion-delay: 20
jump-boots-delay: 40
join-on-join: false
time-until-win: 600